apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: dolibarr
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        image: mariadb:10.6
        name: database
        resources: {}
      restartPolicy: Always
status: {}
