version: "2"

services:
  web:
    image: alexisljn/pmn-dolibarr
    working_dir: /app
    depends_on:
      - "database"
    ports:
      - "80:80"
    volumes:
      - dolibarr-data:/app/htdocs/conf
      - dolibarr-documents:/app/documents
  database:
    image: mariadb:10.6
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dolibarr
      MYSQL_ROOT_PASSWORD: admin

volumes:
  dolibarr-data:
  dolibarr-documents:
  mariadb-data:
