apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dolibarr-documents
  name: dolibarr-documents
spec:
  storageClassName: local-storage
  #  selector:
#    matchLabels:
#      io.kompose.service: web
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
