apiVersion: v1
kind: PersistentVolume
metadata:
  name: dolibarr-data-volume
  labels:
    io.kompose.service: dolibarr-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dolibarr/data
