apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: alexisljn/pmn-dolibarr
        name: web
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /app/htdocs/conf
          name: dolibarr-data
          subPath: htdocs
        - mountPath: /app/documents
          name: dolibarr-documents
          subPath: documents
        workingDir: /app
      restartPolicy: Always
      volumes:
        - name: dolibarr-data
          persistentVolumeClaim:
            claimName: dolibarr-data
        - name: dolibarr-documents
          persistentVolumeClaim:
            claimName: dolibarr-documents
status: {}
