apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: alexisljn/pmn-dolibarr
        name: web
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /app/htdocs
          name: dolibarr-data
        - mountPath: /app/documents
          name: dolibarr-documents
        workingDir: /app
      restartPolicy: Always
      volumes:
      - name: dolibarr-data
        persistentVolumeClaim:
          claimName: dolibarr-data
      - name: dolibarr-documents
        persistentVolumeClaim:
          claimName: dolibarr-documents
status: {}
