apiVersion : apps/v1
kind: Deployment
metadata:
  name: "pmnprojectk8bis-7fc1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "pmnprojectk8bis-7fc1"
  template:
    metadata:
      labels:
        app: "pmnprojectk8bis-7fc1"
    spec:
      containers:
        - name: "pmnprojectk8bis-7fc1"
          image: "pmnprojectcr.azurecr.io/pmnprojectk8bis"
          ports:
          - containerPort: 80