apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-data
  name: mariadb-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azure-disk-db-storage-class
  resources:
    requests:
      storage: 100Mi
status: {}
