apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-data
  name: mariadb-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: my-azurefile-bis
  resources:
    requests:
      storage: 100Mi
status: {}
