apiVersion: v1
kind: Service
metadata:
    name: "pmnprojectk8bis-7fc1"
    labels:
        app: "pmnprojectk8bis-7fc1"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "pmnprojectk8bis-7fc1"