on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pmnprojectcr.azurecr.io
        username: ${{ secrets.acr_pmnprojectcr_username }}
        password: ${{ secrets.acr_pmnprojectcr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pmnprojectcr.azurecr.io/pmnprojectk8bis:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push pmnprojectcr.azurecr.io/pmnprojectk8bis:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pmnprojectk8bis_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep pmn-project-k8sb473 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace pmn-project-k8sb473`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: pmn-project-k8sb473
        container-registry-url: pmnprojectcr.azurecr.io
        container-registry-username: ${{ secrets.acr_pmnprojectcr_username }}
        container-registry-password: ${{ secrets.acr_pmnprojectcr_password }}
        secret-name: pmnprojectk8dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: pmn-project-k8sb473
        manifests: |
          manifests/azure-file-web-storage-class.yaml
          manifests/azure-disk-db-storage-class.yaml
          manifests/dolibarr-data-persistentvolumeclaim.yaml
          manifests/dolibarr-documents-persistentvolumeclaim.yaml
          manifests/mariadb-data-persistentvolumeclaim.yaml
          manifests/database-deployment.yaml
          manifests/web-deployment.yaml
          manifests/service.database.yaml
          manifests/web-load-balancer.yaml
        images: |
          pmnprojectcr.azurecr.io/pmnprojectk8bis:${{ github.sha }}
        imagepullsecrets: |
          pmnprojectk8dockerauth
